var mongoose = require("mongoose");

//This is how a user is represented in our database. 
//The first five rows will be taken from fb authentication.
//The other three rows are relevant to the user's occasions (as viewed in the my occasions page).
var userSchema = mongoose.Schema({
  email: String, 
  token: String,
  fbid: String,
  name: String,
  profilePicture: String,
  createdOccasions: [{type: mongoose.Schema.Types.ObjectId, ref: 'Occasion'}],
  participatedOccasions: [{type: mongoose.Schema.Types.ObjectId, ref: 'Occasion'}],
  receivedOccasions: [{type: mongoose.Schema.Types.ObjectId, ref: 'Occasion'}]
});

/**
 * creates a new user within the schema
 *
 * @constructor
 * @param {String} email the email address of the user 
 * @param {String} token the token generated by facebook when logging in
 * @param {String} fbid the facebook id of the user
 * @param {String} name the name as taken from facebook
 * @param {String} profilePicture the url to the user's facebook profilePicture
 * @param {function} callback a function to be called at the end of the query
 *
 */
userSchema.statics.createNewUser = function (email, token, fbid, name, profilePicture, callback) {
  var self = this;
  self.findOne({ 'email': email }, function (err, user) {
    if (err) {
      callback(err);
    } else if (user) {
      callback({ 'taken': true });
    } else {
      self.create(
        { 
          email: email, 
          token: token, 
          fbid: fbid,
          name: name,
          profilePicture: profilePicture,
          createdOccasions: [],
          participatedOccasions: [],
          receivedOccasions: []
        }, 
        function (er, newUser) {
          if (er) {
            callback(er);
          } else {
            callback(null, newUser);
          }
        }
      );
    }
  });
}

/**
 * returns the user by querying their email address
 *
 * @param {String} email the email address of the user 
 * @param {function} callback a function to be called at the end of the query
 *
 */
userSchema.statics.findByEmail = function (email, callback) {
  this.findOne({ 'email': email }, function (err, user) {
    if (err) {
      callback(err);
    } else {
      callback(null, user);
    }
  });
}

/**
 * returns the user by querying their fbid 
 *
 * @param {String} fbid the facebook id of the user
 * @param {function} callback a function to be called at the end of the query
 *
 */
userSchema.statics.findByFbid = function (fbid, callback) {
  this.findOne({ 'fbid': fbid }, function (err, user) {
    if (err) {
      callback(err);
    } else {
      callback(null, user);
    }
  });
}

/**
 * returns a list of users by querying their fb ids
 *
 * @param {Array} fbids an array of facebook ids of the users
 * @param {function} callback a function to be called at the end of the query
 *
 */
userSchema.statics.findAllByFbid = function (fbids, callback) {
  this.find({ 'fbid': { $in: fbids} }, function (err, users) {
    if (err) {
      callback(err);
    } else {
      callback(null, users);
    }
  });
}

/**
 * returns a list of users by querying their email addresses
 *
 * @param {Array} emails the email addresses of the users
 * @param {function} callback a function to be called at the end of the query
 *
 */
userSchema.statics.findAllByEmail = function (emails, callback) {
  this.find({ 'email': { $in: emails} }, function (err, users) {
    if (err) {
      callback(err);
    } else {
      callback(null, users);
    }
  });
}

/**
 * returns a list of users by querying their ids
 *
 * @param {Array} ids an array of user ids that were generated by mongo
 * @param {function} callback a function to be called at the end of the query
 *
 */
userSchema.statics.findAllById = function (ids, callback) {
  this.find({ '_id': { $in: ids} }, function (err, users) {
    if (err) {
      callback(err);
    } else {
      callback(null, users);
    }
  });
}

userSchema.methods.addCreatedOccasionId = function (occasionId, callback) {
  var self = this;
  self.createdOccasions.push(occasionId);
  self.save();
  callback(null);
}

userSchema.methods.addParticipatedOccasionId = function (occasionId, callback) {
  this.participatedOccasions.push(occasionId);
  this.save();
  callback(null);
}

userSchema.methods.addReceivedOccasionId = function (occasionId, callback) {
  this.receivedOccasions.push(occasionId);
  this.save();
  callback(null);
}

userSchema.statics.removeOccasionFromAll = function (occasionId, creatorId, participantIds, recipientIds, callback) {
  var self = this;

  self.findById(creatorId, function (err, creator) {
    if (err) {
      callback(err);
    } else {
      var i = creator.createdOccasions.indexOf(occasionId);
      if (i != -1){
         creator.createdOccasions.splice(i, 1);
      }
      creator.save();

      self.findAllById(participantIds, function (er, participants) {
        participants.forEach(function (participant) {
          var index = participant.participatedOccasions.indexOf(occasionId);
          if (index != -1){
             participant.participatedOccasions.splice(index, 1);
          }
          participant.save();
        });

        self.findAllById(recipientIds, function (e, recipients) {
          recipients.forEach(function (recipient) {
            var index = recipient.receivedOccasions.indexOf(occasionId);
            if (index != -1){
               recipient.receivedOccasions.splice(index, 1);
            }
            recipient.save();
          });
          
          callback(null);
        });
      });
    }
  });
}

userSchema.statics.findAllOccasions = function (userId, callback) {
  this
    .findById(userId)
    .select('name createdOccasions participatedOccasions receivedOccasions')
    .populate('createdOccasions participatedOccasions receivedOccasions')
    .exec(function (err, user) {
      if (err) {
        callback(err);
      } else {
        user.participatedOccasions = user.participatedOccasions.filter(function (occ) {
          return !occ.isPublished();
        });
        user.receivedOccasions = user.receivedOccasions.filter(function (occ) {
          return occ.isPublished();
        });
        callback(null, user)
      }
    }
  );
}


userSchema.methods.updateProfilePicture = function (newUrl, callback) {
  this.profilePicture = newUrl;
  this.save();
  callback(null);
}

module.exports = mongoose.model("User", userSchema);